import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
// function TopNav(){
//   return(
//     <nav className="flex w-full items-center justify-between p-4 text-xl font-semibold border-b">
//       <div>Gallery</div>

//       <div>Sign In</div>
//     </nav>
//   )
// }
export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode;
              modal: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <body className={`flex flex-col gap-4 font-sans ${GeistSans.variable}`}>
          <div className="grid h-screen grid-rows-[auto, 1fr]">
          <TopNav />
          <main className="overflow-y-scroll"> {children} </main>
           </div>
           {modal}
           <div id="modal-root"></div>
        </body>
      </html>
    </ClerkProvider>
  );
}
